const games = {};

const defaultDeck = [
  "Activist",
  "Medic",
  "Scout",
  "Diplomat",
  "Minister",
  "Diplomat",
  "Commissar",
  "General",
  "Peacekeeper",
  "Sentry Guard",
  "Bounty Hunter",
  "Sentry Guard",
  "General",
  "Sentry Guard",
  "Bounty Hunter",
  "Minister",
  "President",
  "Peacekeeper",
  "Bounty Hunter",
  "Medic",
  "Entrepreneur",
  "Entrepreneur",
  "Activist",
  "Sentry Guard",
  "Minister",
  "Commissar",
  "Medic",
  "Politician",
  "President",
  "Scout",
  "General",
  "Minister",
  "Peacekeeper",
  "Politician",
  "Bounty Hunter",
  "General",
  "Entrepreneur",
  "Peacekeeper",
];

module.exports = {
  games,
  defaultDeck,
};
